# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c93b05bb3fbc020062e87bf600911dc4bf8aadf09cead008f9879bf7173484fb8ae07630fe759120d66916a44f5b82c56756bb6e60b9b40b0b4f2b0c525dc87

test:
  secret_key_base: 7a765f6029f30fdc8714a049c4571d4b0d126577d1270bba81ed19649e2136ff8537004182b00aa656075ea7d754caa62ffe187c9e401d81ce3c1eaa7ea4c9cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
